### ISSUE TITLE
PDF generation fails 

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#95]
PDF generation no longer works. Affected are all types of PDF reports.

Error
```
pdfmake.min.js:12 Uncaught RangeError: Source is too large
    at Uint8Array.set (native)
    at Object.arraySet (http://npa.hrc.co.nz/js/pdfmake.min.js:12:22729)
    at c (http://npa.hrc.co.nz/js/pdfmake.min.js:12:9388)
    at f (http://npa.hrc.co.nz/js/pdfmake.min.js:12:10539)
    at St.g [as func] (http://npa.hrc.co.nz/js/pdfmake.min.js:12:12671)
    at Object.E [as deflate] (http://npa.hrc.co.nz/js/pdfmake.min.js:12:20669)
    at i._write (http://npa.hrc.co.nz/js/pdfmake.min.js:12:7299)
    at http://npa.hrc.co.nz/js/pdfmake.min.js:12:6680
    at i.run (http://npa.hrc.co.nz/js/pdfmake.min.js:11:15810)
    at r (http://npa.hrc.co.nz/js/pdfmake.min.js:11:15444)
```

**Comment by tmfrnz** [comment]
Likely caused by
https://github.com/bpampuch/pdfmake/issues/1113

**Comment by tmfrnz** [comment]
Updating to pdfmake 0.1.32 indeed appears to fix the issue https://github.com/bpampuch/pdfmake/releases/tag/0.1.32

**Comment by tmfrnz** [comment]
- [ ] Footer fails to show page number
- [ ] Footer fails to appear different on title page
